import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const possiblesActions = ["🪨 ROCK", "📄 PAPER", "✂️ SCISSORS"];

  const [userAction, setUserAction] = useState("");
  const [computerAction, setComputerAction] = useState("");
  const [result, setResult] = useState("");
  const [userScore, setUserScore] = useState(0);
  const [computerScore, setComputerScore] = useState(0);

  useEffect(() => {
    if (userAction != "") {
      setComputerAction(possiblesActions[Math.floor(Math.random() * possiblesActions.length)]);
    }
  }, [userAction]);

  useEffect(() => {
    if (userAction != "") {
      setResult(gameRules());
    }
  }, [computerAction]);

  const gameRules = () => {
    if (userAction == computerAction) {
      return "🟰 DRAW";
    }
    if (userAction == "📄 PAPER" && computerAction == "✂️ SCISSORS") {
      setComputerScore(computerScore + 1);
      return "🤖 COMPUTER WINS";
    }
    if (userAction == "🪨 ROCK" && computerAction == "📄 PAPER") {
      setComputerScore(computerScore + 1);
      return "🤖 COMPUTER WINS";
    }
    if (userAction == "✂️ SCISSORS" && computerAction == "🪨 ROCK") {
      setComputerScore(computerScore + 1);
      return "🤖 COMPUTER WINS";
    }
    if (userAction == "📄 PAPER" && computerAction == "🪨 ROCK") {
      setUserScore(userScore + 1);
      return "🙂 USER WINS";
    }
    if (userAction == "🪨 ROCK" && computerAction == "✂️ SCISSORS") {
      setUserScore(userScore + 1);
      return "🙂 USER WINS";
    }
    if (userAction == "✂️ SCISSORS" && computerAction == "📄 PAPER") {
      setUserScore(userScore + 1);
      return "🙂 USER WINS";
    }

    return "";
  };

  return (
    <>
      <Head>
        <title>Chifoumi Technical Test for Lonestone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {userScore == 0 && computerScore == 0 && <p>Get started playing by choosing an action from below</p>}
          {(userScore != 0 || computerScore != 0) && (
            <span>
              <p>
                🤖 : {computerScore} - {userScore} : 🙂{" "}
              </p>
            </span>
          )}
        </div>

        <div className={styles.center} style={{minWidth: 800}}>
          {userAction != "" && (
            <div className={styles.card} style={{ textAlign: "center" }}>
              <h1 className={inter.className}>{result}</h1>
              <br></br>
              <p className={inter.className} style={{ textAlign: "center" }}>
                🙂 {userAction} ✖️ {computerAction} 🤖
              </p>
            </div>
          )}
        </div>
        {userAction != "" && (
          <div
            className={styles.card}
            style={{ cursor: "pointer" }}
            onClick={() => {
              setUserAction("");
              setComputerAction("");
            }}
          >
            <h2 className={inter.className}>Play again ?</h2>
          </div>
        )}

        <div className={styles.grid} style={{ visibility: userAction == "" && computerAction == "" ? "visible" : "hidden" }}>
          <span
            className={styles.card}
            style={{ cursor: "pointer" }}
            onClick={() => {
              setUserAction("🪨 ROCK");
            }}
          >
            <h2 className={inter.className}>
              🪨 ROCK <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Rock destroys Scissors</p>
          </span>

          <span className={styles.card} style={{ cursor: "pointer" }} onClick={() => setUserAction("📄 PAPER")}>
            <h2 className={inter.className}>
              📄 PAPER <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Paper wraps Rock</p>
          </span>

          <span className={styles.card} style={{ cursor: "pointer" }} onClick={() => setUserAction("✂️ SCISSORS")}>
            <h2 className={inter.className}>
              ✂️ SCISSORS <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Scissors cuts Paper</p>
          </span>

          <span
            className={styles.card}
            style={{ cursor: "pointer" }}
            onClick={() => setUserAction(possiblesActions[Math.floor(Math.random() * possiblesActions.length)])}
          >
            <h2 className={inter.className}>
              🔮 RANDOM <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Feeling lucky?</p>
          </span>
        </div>
      </main>
    </>
  );
}
